title: JackAce
author: Jack Hayes
avatar_url: https://en.gravatar.com/userimage/16333631/fd0ff7b3a6145af790737011dc6b2272.png?size=300
description: > # this means to ignore newlines until next section
  Gambling. Crypto. Math.
repository: JackAce/jackace.com

# Google Analytics
google_analytics: G-0HYRRBTEVY

contact:
  url: https://github.com/JackAce

# Settings for Hamilton theme
avatar: https://en.gravatar.com/userimage/16333631/fd0ff7b3a6145af790737011dc6b2272.png?size=300
location: Southern California
skin: midnight
date_format: "%-d %b %Y"
# Settings for Hamilton theme

# Subscribe Feed
#
# By default, your site generates a subscription feed (RSS/Atom) at /feed.xml
# Uncomment the next two lines to change the path.
feed:
   path: /feed.xml

# Homepage
show_excerpts: true  # set to true to show excerpts on the homepage, otherwise full posts are shown

# Comments
# To enable comments, set the `enabled` field to true and supply either a Disqus short name or a Jekyll comments receiver
disqus: jackace-beta
comments:
  enabled: false
  #disqus: jackace

  #show_count: true
  #receiver:

# Jekyll Settings
#
permalink: /blog/:year/:month/:day/:title/
paginate: 20
page_group_size: 5 # number of pages to group by in the pagination.
paginate_path: "/archive/page/:num"
category_dir: categories

# Build settings
markdown: kramdown
kramdown:
  hard_wrap: false
remote_theme: jackacestudios/jekyll-theme-hamilton

exclude: [README.md CODE_OF_CONDUCT.md script .gitattributes .gitignore keybase.txt RakeFile]
keep_files: [images demos code ads.txt robots.txt favicon.ico]
incremental: true

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
  #- jemoji
